export { dashboardRoutes } from './dashboard/config/dashboard.routes';
export { dashboardMenuItems } from './dashboard/config/dashboard.menu';
export { simulationRoutes } from './simulation/config/simulation.routes';
export { simulationMenuItems } from './simulation/config/simulation.menu';
export { meetingRoutes } from './meeting/config/meeting.routes';
export { meetingMenuItems } from './meeting/config/meeting.menu';
export { reportRoutes } from './report/config/report.routes';
export { reportMenuItems } from './report/config/report.menu';
export { adminReferenceRoutes } from './admin-reference/config/admin-reference.routes';
export { adminReferenceMenuItems } from './admin-reference/config/admin-reference.menu';
export { pmoRoutes } from './pmo/config/pmo.routes';
export { deliverableRoutes } from './deliverables/config/deliverables.routes';
export { deliverableMenuItems } from './deliverables/config/deliverables.menu';
export { simulatedEmailRoutes } from './simulated-emails/config/simulated-emails.routes';
export { simulatedEmailMenuItems } from './simulated-emails/config/simulated-emails.menu';
export { profileRoutes } from './profile/config/profile.routes';
export { profileMenuItems } from './profile/config/profile.menu';
export { valorizationRoutes, badgeVerifyRoute } from './valorization/config/valorization.routes';
export { valorizationMenuItems } from './valorization/config/valorization.menu';
export { recruitmentRoutes, recruitmentJoinRoute } from './recruitment/config/recruitment.routes';
export { recruitmentMenuItems } from './recruitment/config/recruitment.menu';
export { mentoringRoutes } from './mentoring/config/mentoring.routes';
export { mentoringMenuItems } from './mentoring/config/mentoring.menu';
